### ISSUE TITLE
Add some CI

### ISSUE THREAD

**Issue by alainmeier** [opendoor-labs/cognito#18]
Would be nice to get some CI going. Does OD use anything we could/should piggyback off of or can I setup something up w/ Circle or Travis?

**Comment by connorjacobsen** [comment]
@alainmeier We use Circle. Ill set that up tomorrow.

**Comment by alainmeier** [comment]
I have added a circle config to https://github.com/opendoor-labs/cognito/pull/24. All that should be required is for you to add it to Circle
